cvprofile/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, re_path, include
# from intro.views import about as aboutme
# from intro.views import desc as description
# from intro.views import msg as message
# from intro.views import homepage as home
# from intro.views import jadwal_detail as jadwal


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    
]

intro/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static

app_name = 'intro'

urlpatterns = [
    path('', views.homepage, name="home"),
    path('about/', views.about, name="about"),
    path('contact', views.msg, name="contact"),
    path('desc', views.desc, name="desc"),
    path('susunjadwal', views.formSchedule, name="susunJadwal"),
    path('submitSchedule', views.susunSchedule, name="submitSchedule"),
    path('allSchedule',views.allSchedule, name="allSchedule"),
    path('deleteSchedule', views.deleteSchedule, name="deleteSchedule"),
    # path('detail', views.jadwal_detail),
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

intro/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=200)
    hari = models.CharField(max_length=20)
    tanggal = models.DateField()
    waktu = models.TimeField()
    tempat = models.CharField(max_length=200)
    kategori = models.CharField(max_length=200)

intro/forms.py
# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Layout, Submit

from django import forms
from .models import Jadwal
class Schedule(forms.Form):
    nama_kegiatan = forms.CharField(label='Nama Kegiatan')
    hari = forms.CharField(label="Hari")
    tanggal = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    waktu = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    tempat = forms.CharField(label="tempat")
    kategori = forms.CharField(label = "Kategori")

intro/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Jadwal
from intro.forms import Schedule
# from intro.forms import JadwalForm

def homepage(request):
    return render(request, "home.html", {})
def about(request):
    return render(request, "index.html", {})
def msg(request):
    return render(request, "form.html", {})
def desc(request):
    return render(request, "description.html", {})

def allSchedule(request):
    schedules = Jadwal.objects.all()
    return render(request, 'form_result.html', {'schedules':schedules})


def deleteSchedule(request):
    schedules = Jadwal.objects.all().delete()
    return render(request, 'form_result.html', {'schedules':schedules})

def formSchedule(request):
    form = Schedule()
    return render(request,'forms.html', {'form':form})

def susunSchedule(request):
    form = Schedule(request.POST)
    if form.is_valid():
        hari = request.POST.get("hari")
        tanggal = request.POST.get("tanggal")
        waktu = request.POST.get("waktu")
        nama_kegiatan = request.POST.get("nama_kegiatan")
        tempat = request.POST.get("tempat")
        kategori = request.POST.get("kategori")
        Jadwal.objects.create(nama_kegiatan=nama_kegiatan, hari=hari, waktu=waktu, tanggal=tanggal, tempat=tempat, kategori=kategori)
        # schedules = Jadwal.objects.all()
        # return render(request, 'form_result.html', {'schedules':schedules})
        return redirect('intro:allSchedule')
    else:
        return render(request, 'forms.html', {})

intro/templates/form_result.html
<!DOCTYPE html>
<html>
<head>
	<title>All Schedule</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Istok+Web:700|Karla:400,700" rel="stylesheet">
	{% include "navbar.html" %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% load static %}
	<link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>
	
</head>
<body>
    {% if schedules %} 
        <div class="table-responsive">
            <table class="table table-hover">
                <tr>
                    <th>Kegiatan</th>
                    <th>Hari/Tanggal, Waktu</th>
                    <th>Tempat</th>
                    <th>Kategori</th>
                </tr>
                {% for item in schedules %}
                <tr>
                    <td>{{ item.nama_kegiatan }}</td>
                    <td>{{ item.hari }} {{ item.tanggal }} {{ item.waktu }}</td>
                    <td>{{ item.tempat }}</td>
                    <td>{{ item.kategori }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        
    {% else %}
        <h2>Tidak ada jadwal</h2>
    {% endif %}
    <form action="{% url 'intro:deleteSchedule' %}">
        <button type="submit" class="btn btn-danger">Delete All</button>
    </form>
   





</body>
</html>

intro/templates/forms.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% include "navbar.html" %}
        <title>Add Your Schedule</title>
        <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=Istok+Web:700|Karla:400,700" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
        
    <body>
        <div class = "container form">
            <div id="nav-placeholder"></div>
            <script>
                $(function) {
                    $("#nav-placeholder").load("navbar.html");});
                }
            </script>
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                        <Section name="form">
                                <h2>Add your schedule!</h2>
                                <form id="form" method="POST" action="{% url 'intro:submitSchedule' %}">
                                    {% csrf_token %}
                                    {% for item in form %}
                                    <div class="form-group">
                                        <label>{{ item.label_tag }}</label>
                                        {{ item }}
                                    </div>
                                    {% endfor %}
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                
                            </Section>
                </div>
            </div>
            
        </div>
    </body>
</html>

intro/templates/home.html
<!DOCTYPE html>
<html>
    <head>
            <title>Hello!</title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            {% include "navbar.html" %}
            <link href="https://fonts.googleapis.com/css?family=Istok+Web:700|Karla:400,700" rel="stylesheet">
            {% load static %}
            <link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>
        <style>
            body {
                height: 100%;
                width: 100%;
                padding: 0;
                margin: 0;
                background-image: url("https://lh3.googleusercontent.com/f3pSQzvbnMc6JEXOrefxswFrX13-KKoVSPIoRjabGsma2FF3w9_BM6bUZ27cMauMhJ8eUz9wYwvnYC-oldLVqfQiDvlbUuP7JbA4dg2I0B0lSjlBLg6KyVzWw_veKXRB0uOab-DBZbBFRB55t3Mcp5hrSdX02yDw3O1JTPsqdBf0pTDETQrATz2nGNkQfsWR2uMTiohZHruiXorUhwXAoqxXd4RtPz0v0yiNyB442U_cVkCKcyxNbk8NrrSusjjX7GJXGwzUOVl5xef3pywNPRIYQqXExxrR75Zul9C_x8rp0cWCc_cENG7vfW79Xrw3mnwPLzXPkZT9oUDM5Km4ALKua98JbwKfJWF2IeKDCzsEKBQeFQFVivHs2qTchDS9p1ZBHdGrWNoljk7iYh9mGOL-yO6ICe5HT496bcYiBDYbTiJRWjOotPkpIiRb79yUR0vxyyt7yyyq-58ftnaBFhORBt4ly3GuB-d5T3tNi7c1pTvRlaacuG6tWhmEgLQE00qjuEgI2p2n9RpsNJVzqpNVi6BtihtIjdv2OBuf6V1BtdSr7nIJUoMF9cJsPEAf9mTGj7zEBvR5vPZH0POsQYm02ozGNGFgygI51PJdOLOP0mrqJu1C8dJIZ7A0wrg=w1302-h926-no");
                background-repeat: no-repeat;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
                /* font-family: 'Istok Web', sans-serif; */
            }
            /* h1 {
                font-family: Istok Web;
                font-style: normal;
                font-weight: bold;
                line-height: 80%;
                font-size: 180px;

                color: #DE9F53;
                margin: 0px;
                position: static;
                box-sizing: border-box;
            } */
            /* h2 {
                /* font-family: Karla;
                font-style: normal;
                font-weight: bold;
                line-height: normal;
                font-size: 40px;

                color: #FFFFFF; 
            } */
        </style>
    </head>
    <body>
        <div class= "home container">
                <div id="nav-placeholder">

                    </div>
                    <script>
                        $(function) {
                            $("#nav-placeholder").load("navbar.html");});
                        }
                    </script>
            <div class= "row">
                <div class="col-2"></div>
                <div class= "col-6">
                        <h2>Hello, My Name is</h2>
                </div>
            </div>
                <div class= "row align-items-center" >
                    <div class="col-4"></div>
                        <div class= "col-3">
                                <h1>FAKHIRA</h1>
                                <h1>DEVINA</h1>
                                
                        </div>
                        
                </div>
                <div class="row fixed-bottom">
                    <div class="col-5"></div>
                    <div class="col-3">
                            <div class="txts">
                                    <h3 class="text-center font-italic">Want to know more?</h3>
                                    <a href="{% url 'intro:about' %}"><img src="https://lh3.googleusercontent.com/eN6XEc7T0jZ02k8sCl3NHc55OP5JjGr1ma_K_7puBfq581IwO07EymcoDcGc5fZxwpHBBwRcep_jdXR-Y0OYp5vZ_CeQMrS3XKVD_aQdXmOvMJjJrN4-3Isl8rhddeiIPvaWTdKmYns3YzXR5e5wVLYRATODVMocZ8GREnKO56SHIcmaVAlG2sKCy3yEmzhukZMrJ4MO0fHyK7C25L2mirmcnTJc0WiqwS_4wpEcTbKUhXpwQa7ayjvJKYk1U8sTA52sqXFJZOlE21yBOpbXMDDAsOirwEtwdkcA_EjFwdP6IY7bjaZBh8B-9NmD5PPQWrz80np8afKIDcUzo_IWppHiQV5UPihyvk0XfzltzpRBzi0_kDkWjWdDPMviVjWRHnou_v7a-TvNOuvKe-hlHr98-zh9226nKpcfR7rUrcU2B6uIWnTJ9zIJpLycOnDTgtpoiNPgGJ9XKSCt2CTPckyG35htl0oHDxxo7Ng9NKEow-VLPkYHjrksy5NMyXygcNYpnCb_DRsH2D7yUYON-0_efSoMzi-efEKTSx_A8YNMBoIgRR1NxXarJQqj2OdeOitRWKbfmxwk_ctKxMWhBj5l-2Twnj-l92EqrCS8baWGS6TihXo2nlc1DXOuIbc=s256-no"width="60" height="60"></a>
                            </div>
                    </div>
                </div>
                
                
            
            
        </div>
        
    </body>
</html>

intro/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Know Hira More</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Istok+Web:700|Karla:400,700" rel="stylesheet">
	{% include "navbar.html" %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% load static %}
	<link href="{% static "style.css" %}" type="text/css" rel="stylesheet"/>
	
</head>
<body>
	
	<div class="container-fluid">
		<div id="nav-placeholder">

		</div>
		<script>
			$(function) {
				$("#nav-placeholder").load("navbar.html");});
			}
		</script>
		<!-- <nav class="navbar navbar-light sticky-top" style="background-color: #243346;">
				<a class="nav-link" href="desc">About me</a>
				<a class="nav-link" href="homepage">Home</a>
				<a class="nav-link" href="msg">Contact</a>
				
		</nav> -->
		<div class="row">
				<div class="col-4 col-md-4">
					<div class="fixx">
							<div class="bio half">
									<h1>FAKHIRA</h1>
									<h1>DEVINA</h1>
									<h3 id="npm">NPM 1706979221</h3>
									<h3>Faculty of</h3>
									<h3>Computer Science 2017</h3>
									<h2>Contact</h2>
									
									<h4><img src="https://lh3.googleusercontent.com/mYy_gY3wp1alrZXJ8B8EEVlbrKQ88hXkAwLvH_bwE7jzL3MaNX8wZyFXNILwk66FZ7SgRCWv5QUFM9rA-77ierhdAiufZJDvFTcr-KdktA6emonNkrACOIVi7qT7ppAyqfZ8xk78H0o91bhH0u0qj0ITCKD40NDoGahkpiERNR1FJxu3SvPy7ZMJyd1F_GbTXpPQpXsdebBfB_JR7qzCvkfWVTOaMhCLLJKMUTQY3meeotHaj7tWRiOYuq16CrqYcK_GRecZJhKtz1yc07Woxii3nFouw7NG8eu3K7DgeHDBSFl-YLJsr4U9NTRsNzMrGUnY9sCUhBUpwFJeTb2-G2lhytx3zBYdI1MPcrg_TG80uB2Fj0Ifx3IQ1Ac7oJdWs64HDhR0GdeZ2VQujB_dHhuoPoYthi_AVl1L4LfJyhG-I7EPNDJCKI4jHMuSgP8RC7EUjr4YTBxNRx_1Nn3yob71NFWr3EiIueDuWvNWR3ChRQtg1P5hmpymzRIG-THtIRd_8hjihuXa7uk-wzUqUp7mR2ds-OdqDtz2fg_QxyxoEhqWOZgFl4m7k8SABJUFdms228PvLnTD2szWdcVP3oWD2xcOcGlOLCGQ7wWF7CFeFH_Jq_IDeGULnlk5ntY=s64-no" width="20" height="20" class="phone img">087884483720</h4>
									<a href="{% url 'intro:contact' %}" target="_blank"><h4>Send me a message</h4></a>
									<div class="row">
											<div class="col-1">
													<a href="https://lh3.googleusercontent.com/K5afvpGq-U9AamYqCt003DviwMLyOMal-bBc7eVMxmYMPTAxGdZp-_Yt_NJNjup0uGiQPz3ymjWLlB3XK5OoDXNdXV-0Wboj2nfNB-HbfdTqcqrhjGjwe2PgdBl1bqFfQHABHPmmhUFZC7wlhOsHEwMHfM2v3LRP-BoMZWQzSEueYo7xH6Y2sqOudOfSecYV5y4gghYEzv8-5lNZYEbsKjX5TzYCkoQ8gH9WF1-sMtsdSGeeJGlWNTvRA2iKFvIWP51Z_wSz-Wkp08yHSjZDHaGSJS-35KCeP8dBcvHe63bFMsoU-Y8TuTLiVr0IzDrZVql7aUgnR43a7gfApa1qFKaYktnWAKVpacg_X2-GwnvxSxH2jthhY57oGLP0KRN5eaKWe_2MKm0pgg4cujmkYoWw_wypPmD7hDBZy_ecSEerSnSOAo5_Pq-bDosRA_TGYu_qAZIcavMU8uVAwqCJuEOh4kbhdKjwkt6GgExUzeVRcSlJkb2fNRBkxcUMmu78kq5N3wmepkhfDdk5J_cc70BuK_wWrOuSc9xSH-UEIVEXk5YRnelYOMJNikE4KRIZZrCLR7pag07tgCH1-FRlZIZf9PZiMWjyfIUW4XksomfWzxjJpUjuUxJc3WVQlHU=w716-h926-no" target="_blank"><img src="https://lh3.googleusercontent.com/qH-zDBX8iai9wZQJKFFXE7vl5nd6wG1QuepCuBi56hDAHYQ3sDoIJ1Gp1Ms55qA_g_s_cyU5l1PlPyScPjCZGL8n1avkYYs90s1AgdLW2Q0Yvc0KAFPxkmaLB3XS7XaOXpcyfsbt8rpmkjJzoS3kFkeYzZ0UoKuNZ4DnCVavvrCCxvisxBmwFK1Ef1prj8yFTgaq7B6ZdMP3L20tuciziSTfUZPpjU0bqzWy_9PdYaGK5gnZ3bfPMMmEJiWRuTpu2rUP1ALY9WBOpR4NESauzguEHTvUelu-Q91OuKwhHyZbTa2pdsLzYsGPsMcGeOfkSk71l48ahdTiCRj568gXeE6XMzqlLoDP0hfJh4RAVK-VFyIJJ8HLc2zLpEn5MAWdRpJc3YhtPOx9rZZAZrhoaKd-YHb375Vis_Sch0_xjB1ZAdj2wrAWBHypWqHBaRvli9MpZC0fVCtFVLI85synu6k8ztjSPPDnoF0B5VLMAbYv7ohlT-TrBuFaKB_DXDsQwDO0upugJaNLBNMKU2fJyuhDGKzJ_33yKypHV_4lxGlKC82Fz68huX9T3M2S838ntd5yJ5IPLVGqp4GMRcQITxyxKDpNBMWbmlDgaXPcFOQLFACFfYi2YRAGzf7nTM8=s926-no" alt="Download" width="40" height="40" class="clickable img"></a>
											</div>
											<div class="col-1">
													<a href="https://www.linkedin.com/in/fakhira-d-4497a3112/" target="_blank"><img src="https://lh3.googleusercontent.com/FfNyVWUrOZ7KTHJrawAHVu8RGpRvvfO2onBv-WIllFEvkEGBHbLwoxBPrc7kBdZp6tpB2kM3ZT2C0YH9BNBHs-0yzdHgQibxqz5cA3JiR2nhsdPlSK9eWoHEJeKtmM1WOmHNlYa9I2pUz0abwWFt2-kuVF8wx1AIyVVM4etUfL_HQSsuXqUeaeptQ6oE8xRNqOdin7GDJikIgfF41KkbuRHo3N-L65kEcHqPMewA-kCe4u1o2KDgS5oNo8RVA3mKGEcCKEmLnqigIj91ogtJ_StxjMbLJSeRo_7R9Izym7fp3_Rp6Fbj5Y32ACrPs_x_f954tPEnfeQEljIeZ7s8vP_CpdCiz96VXDugcrahaBmylmya-9dMckjxPu6CbKiSXF8X2op9Fth80kWGMcnhmiK4CZY7TQF6VI8vcwMPOi3ZMMSXvvEmNrsWpEfMC-H-2goglLVA7xIQPcFu8br2uVxtaxchYxa9FUi04WtSUQK1kh1d-_qr2AFPqUdZk8utaL9EjeXrdBAKc2k7AE7s-vwwu81cOAzm4BGK1n3hw6-3pYBH2JcZBRPbMH2q2xmWt1V6hQOmEIsKYBAUXU0XSMBdLjmlFtgsDRBjfurw2RgTf_75mRF-fVrXPTIqxNc=s64-no" width="40" height="40" alt="LinkedIn" class="clickable img"></a>
											</div>
									</div>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
									<br>
								
								</div>
					</div>
					
						
				</div>
				<div class="col-8 col-md-8">
					<div class="fulldes half">
							<div class="description">
									<h2>Description</h2>
									<p>A freshman Computer Science student who loves on learning about new things and gaining new experiences</p>
								</div>
								<div class="education">
									<h2>Formal Education</h2>
									<h4>SD Islam Al-Azhar 20 Cibubur</h4>
									<h5>2005-2011</h5>
									<h4>SMP Labschool Cibubur</h4>
									<h5>2011-2014</h5>
									<h4>SMAN 2 Depok</h4>
									<h5>2014-2017</h5>
									<h4>Universitas Indonesia</h4>
									<h5>Faculty of Computer Science | 2017 - Present</h5>
								</div>
								<div class="experiences">
									<h2>Experiences</h2>
									<h4>AKAR 2017</h4>
									<h5>Publication and Design Staff | 2017</h5>
									<p>AKAR is an annual art event in SMAN 2 Depok as a forum for students to show their ability in art.</p>
									<ul>
										<li>Designed merchandises (shirt, cap, etc)</li>
									</ul>
									<h4>Yearbook Project</h4>
									<h5>Creative Staff | 2017</h5>
									<ul>
										<li>Decided the yearbook theme</li>
										<li>Designed templates and packaging </li>
									</ul>
									<h4>Wisuda Ganjil</h4>
									<h5>Creative Staff | 2018</h5>
									<ul>
										<li>Made decorations for the venue</li>
									</ul>
									<h4>COMPFEST X</h4>
									<h5>Visual Design Staff | 2018 - present</h5>
									<p>Compfest is an annual IT event held by Fasilkom UI's students</p>
									<ul>
										<li>Made publication posters, certificate templates, ID cards, etc.</li>
									</ul>
									<h4>Wisuda Genap Fasilkom UI</h4>
									<h5>Creative Staff | 2018</h5>
									<ul>
										<li>Made publication posters, powerpoint template.</li>
									</ul>
									<h4>Pembinaan Mahasiswa Baru Fasilkom UI 2018</h4>
									<h5>Documentation Staff | 2018 - present</h5>
									<ul>
										<li>Made teaser video and after movie video.</li>
									</ul>
								</div>
								<div class="skill">
									<h2>Skills</h2>
									<div class="row">
											<div class="col-4">
													<ul>
														<li>English</li>
														
													</ul>
													<br>
													<ul>
														<li>German</li>
														
													</ul>
													<br>
													<ul>
														<li>Adobe Photoshop</li>
														
													</ul>
													<br>
													<ul>
														<li>Adobe Premiere</li>
														
													</ul>
													<br>
													<ul>
														<li>Python</li>
														
													</ul>
													<br>
													<ul>
														<li>HTML</li>
														
													</ul>
												</div>
												<div class="col-5">
														<div class="progress"   style="height:13px">
																<div class="progress-bar bg-success" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" item-height="40"   style="height:13px"></div>
														</div>
														<br>
														<br>
														<div class="progress"   style="height:13px">
																<div class="progress-bar bg-success"  role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"   style="height:13px"></div>
														</div>
														<br>
														<br>
														<div class="progress"   style="height:13px">
																<div class="progress-bar bg-success" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"   style="height:13px"></div>
														</div>
														<br>
														<br>
														<div class="progress"   style="height:13px">
																<div class="progress-bar bg-success"  role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"   style="height:13px"></div>
														</div>
														<br>
														<br>
														<div class="progress"   style="height:13px">
																<div class="progress-bar bg-success"  role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"   style="height:13px"></div>
														</div>
														<br>
														<br>
														<div class="progress"   style="height:13px">
																<div class="progress-bar bg-success"  role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"   style="height:13px"></div>
														</div>
			
			
												</div>
									</div>
									
									
								</div>
								<div class="personality">
									<h2>Personality Highlights</h2>
									<ul>
										<li>Creative</li>
										<li>Responsible worker</li>
										<li>Well organized</li>
										<li>Works on schedule</li>
										<li>Easily motivated on learning new things</li>
									</ul>
								</div>
					</div>
				</div>
		
			

		</div>
		
		
	</div>

		
			
		


</body>
</html>

intro/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static "style.css" %}">
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

</head>
<body>
	<nav class="navbar navbar-light sticky-top" style="background-color: #243346;">
		<a class="nav-link" href="{% url 'intro:desc' %}">About me</a>
		<a class="nav-link" href="{% url 'intro:home' %}">Home</a>
		<a class="nav-link" href="{% url 'intro:contact' %}">Contact</a>
		
		<a class="nav-link" href="{% url 'intro:susunJadwal' %}">Jadwal</a>
		
</nav>  
</body>